CREATE TABLE CIDADES (
  ID_CIDADES INT IDENTITY,
  NOME VARCHAR(50),
  ESTADO VARCHAR(2)
  CONSTRAINT PK_CIDADES PRIMARY KEY (ID_CIDADES))
GO
CREATE TABLE CLIENTES (
  ID_CLIENTES INT IDENTITY,
  NOME VARCHAR(50) NOT NULL,
  CPFCPNJ VARCHAR(20) NOT NULL,
  IERG VARCHAR(15),
  TIPO TINYINT,
  ENDERECO VARCHAR(100),
  TELEFONE VARCHAR(150),
  ID_CIDADES INT
 CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTES),
 CONSTRAINT FK_CLIENTES_CIDADES FOREIGN KEY (ID_CIDADES) REFERENCES CIDADES (ID_CIDADES))
 